#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service flocore stop || echo "flocore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "flocore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "flocore.service" || echo "flocore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so flocore could not be stopped"
fi
